version: '3'
services:
    dividend_app:
        build:
            context: build
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            PORT: 5000
            FMP_API_KEY: ${FMP_API_KEY}
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            OPENAI_MODEL: ${OPENAI_MODEL}
            PYTHONUNBUFFERED: 1